---
- hosts: localhost
  tasks:
    - name: Generate configuration file
      template: src=/Users/tewks/projects/pynet/repo/ansible/access_switch.j2
                dest=/Users/tewks/projects/pynet/repo/ansible/{{item.hostname}}.txt

      with_items:
        - {hostname: pynet-rtr1, secret: abc123, access_vlan: 5, ip_addr: 1.1.1.10, default_gateway: 1.1.1.1, snmp_community: foobar, SNMP3: True }
        - {hostname: pynet-rtr2, secret: abc123, access_vlan: 5, ip_addr: 1.1.2.10, default_gateway: 1.1.2.1, snmp_community: foobar, SNMP3: True }
        - {hostname: pynet-rtr3, secret: abc123, access_vlan: 5, ip_addr: 1.1.3.10, default_gateway: 1.1.3.1, snmp_community: foobar, SNMP3: True }
        - {hostname: pynet-rtr4, secret: abc123, access_vlan: 5, ip_addr: 1.1.4.10, default_gateway: 1.1.4.1, snmp_community: foobar, SNMP3: False }
        - {hostname: pynet-rtr5, secret: abc123, access_vlan: 5, ip_addr: 1.1.5.10, default_gateway: 1.1.5.1, snmp_community: foobar, SNMP3: False }
        - {hostname: pynet-rtr6, secret: abc123, access_vlan: 5, ip_addr: 1.1.6.10, default_gateway: 1.1.6.1, snmp_community: foobar, SNMP3: False }
